openapi: 3.0.3
info:
    title: Order Mangament Service
    description: Microservice for manager Order
    version: "1.0"
servers:
    - url: http://localhost:30001
paths:
    /api/v4/msorderms/order:
        post:
            tags:
                - msorderms
            summary: createOrder msorderms
            operationId: msorderms#createOrder
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateOrderRequestBody'
                        example:
                            cognomeCliente: Facilis est consectetur enim expedita consectetur.
                            dataOrdine: Aspernatur dignissimos voluptatibus architecto id.
                            idOrdine: Et soluta rerum aut.
                            nomeCliente: Sapiente aut ipsam adipisci voluptatum modi.
                            righeOrdine:
                                - barcode: Et consectetur.
                                  colore: Voluptatem non sunt ea.
                                  modello: Alias tenetur.
                                  prezzo: 0.78429174
                                  quantita: 7708216444412231043
                                  taglia: Nobis minima sit a qui.
                                - barcode: Et consectetur.
                                  colore: Voluptatem non sunt ea.
                                  modello: Alias tenetur.
                                  prezzo: 0.78429174
                                  quantita: 7708216444412231043
                                  taglia: Nobis minima sit a qui.
                            store: Sed ut reiciendis quisquam ipsa.
                            tipologiaOrdine: negozio
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StatoOrdine'
                            example:
                                ordineId: Accusamus reiciendis sint aperiam repellendus quae excepturi.
                                statoOrdine: da elaborare
                "400":
                    description: 'no_criteria: Bad Request response.'
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Earum voluptas.
    /api/v4/msorderms/order/{idOrdine}:
        get:
            tags:
                - msorderms
            summary: getStatusOrderById msorderms
            operationId: msorderms#getStatusOrderById
            parameters:
                - name: idOrdine
                  in: path
                  description: IdOrdine
                  required: true
                  schema:
                    type: string
                    description: IdOrdine
                    example: Ut mollitia consequatur eum natus.
                  example: Facere veritatis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StatoOrdine'
                            example:
                                ordineId: Quis eum.
                                statoOrdine: da elaborare
                "404":
                    description: 'no_match: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/v4/msorderms/sayHello:
        get:
            tags:
                - msorderms
            summary: sayHello msorderms
            operationId: msorderms#sayHello
            parameters:
                - name: name
                  in: query
                  description: Name
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Name
                    example: Eos aliquid corporis.
                  example: Ipsam reiciendis omnis aut velit aliquid.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Vel ut accusamus maiores pariatur iusto saepe.
                            example: Commodi exercitationem ut.
    /swagger/swagger.json:
        get:
            tags:
                - swagger
            summary: Download gen/http/openapi.json
            description: JSON document containing the API swagger definition
            operationId: swagger#/swagger/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateOrderRequestBody:
            type: object
            properties:
                cognomeCliente:
                    type: string
                    description: Cognome Cliente
                    example: Dolorem accusantium dolor nam assumenda et atque.
                dataOrdine:
                    type: string
                    description: Data Ordine
                    example: Blanditiis architecto dolores sed ratione placeat deleniti.
                idOrdine:
                    type: string
                    description: Id Ordine
                    example: Alias alias quae quia pariatur autem porro.
                nomeCliente:
                    type: string
                    description: Nome Cliente
                    example: Rem id.
                righeOrdine:
                    type: array
                    items:
                        $ref: '#/components/schemas/RigaOrdine'
                    description: Righe Ordine
                    example:
                        - barcode: Et consectetur.
                          colore: Voluptatem non sunt ea.
                          modello: Alias tenetur.
                          prezzo: 0.78429174
                          quantita: 7708216444412231043
                          taglia: Nobis minima sit a qui.
                        - barcode: Et consectetur.
                          colore: Voluptatem non sunt ea.
                          modello: Alias tenetur.
                          prezzo: 0.78429174
                          quantita: 7708216444412231043
                          taglia: Nobis minima sit a qui.
                        - barcode: Et consectetur.
                          colore: Voluptatem non sunt ea.
                          modello: Alias tenetur.
                          prezzo: 0.78429174
                          quantita: 7708216444412231043
                          taglia: Nobis minima sit a qui.
                        - barcode: Et consectetur.
                          colore: Voluptatem non sunt ea.
                          modello: Alias tenetur.
                          prezzo: 0.78429174
                          quantita: 7708216444412231043
                          taglia: Nobis minima sit a qui.
                store:
                    type: string
                    description: Codice Store
                    example: Quia et qui nobis aut.
                tipologiaOrdine:
                    type: string
                    description: Tipologia Ordine
                    example: negozio
                    enum:
                        - corriere
                        - negozio
            example:
                cognomeCliente: Ipsa numquam quia repudiandae.
                dataOrdine: Vel aut vitae dolor.
                idOrdine: Blanditiis accusantium in.
                nomeCliente: Velit possimus dolor magnam dolor pariatur.
                righeOrdine:
                    - barcode: Et consectetur.
                      colore: Voluptatem non sunt ea.
                      modello: Alias tenetur.
                      prezzo: 0.78429174
                      quantita: 7708216444412231043
                      taglia: Nobis minima sit a qui.
                    - barcode: Et consectetur.
                      colore: Voluptatem non sunt ea.
                      modello: Alias tenetur.
                      prezzo: 0.78429174
                      quantita: 7708216444412231043
                      taglia: Nobis minima sit a qui.
                store: Aut animi qui eos sit.
                tipologiaOrdine: corriere
            required:
                - idOrdine
                - store
                - tipologiaOrdine
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        RigaOrdine:
            type: object
            properties:
                barcode:
                    type: string
                    description: Barcode Articolo
                    example: Dolores tempore sit pariatur ea.
                colore:
                    type: string
                    description: Codice Colore
                    example: Quia facere rem illum aut.
                modello:
                    type: string
                    description: Codice Articolo
                    example: Odio id quas culpa.
                prezzo:
                    type: number
                    description: Prezzo
                    example: 0.6035357
                    format: float
                quantita:
                    type: integer
                    description: Numero pezzi
                    example: 6970700527459960448
                    format: int64
                taglia:
                    type: string
                    description: Codice Taglia
                    example: Voluptate et et.
            example:
                barcode: Quisquam beatae asperiores qui aut.
                colore: Eum hic.
                modello: Sed doloribus.
                prezzo: 0.52175874
                quantita: 1730267733055539616
                taglia: Voluptatem animi commodi qui.
            required:
                - barcode
                - quantita
        StatoOrdine:
            type: object
            properties:
                ordineId:
                    type: string
                    description: Id Ordine
                    example: Laboriosam dolorum quod qui.
                statoOrdine:
                    type: string
                    example: presa in carico
                    enum:
                        - da elaborare
                        - in elaborazione
                        - presa in carico
                        - confermato
                        - annullato
            example:
                ordineId: Perferendis quas atque.
                statoOrdine: presa in carico
tags:
    - name: msorderms
      description: The service manager order
    - name: swagger
      description: The swagger service serves the API swagger definition.
